### ISSUE TITLE
migrate to jupysql?

### ISSUE THREAD

**Issue by edublancas** [Ash021980/Airbnb-Case-Study#1]
Hey, I noticed you're using ipython-sql.

Since the package is no longer maintained, [I forked it](https://github.com/ploomber/jupysql) and added some cool features like plotting large datasets by running data aggregations in the warehouse, CTE composition, among others!

It remains fully compatible, so you don't have to change your code!

I'd highly appreciate your feedback, as I'm looking for suggestions on what new features to build next.

**Comment by Ash021980** [comment]
I will check the features and let you know what I think.  Thank you.

**Comment by edublancas** [comment]
awesome!
